### ISSUE TITLE
Error: Node not found: KeyName

### ISSUE THREAD

**Issue by koitaki** [11ty/eleventy-navigation#23]
Exhausted all thoughts on what could be causing this, and wondering if anyone else has a hint.
My front matter has this:

```
eleventyNavigation:
    key: Alphabet
    parent: IPA
```

I've tested this and it works fine, returning all children, including Alphabet:
```
{% set breadcrumbs = collections.all | eleventyNavigation("IPA") %}
{{ breadcrumbs | eleventyNavigationToHtml | safe }}
```

But this breaks & gives me "Error: Node does not exist: Alphabet":
```
{% set breadcrumbs = collections.all | eleventyNavigationBreadcrumb("Alphabet") %}
{{ breadcrumbs | eleventyNavigationToHtml | safe }}
```

Sadly its the latter that I'm after, for my breadcrumb navigation.

Thanks in advance if anyone has any useful suggestions or ideas why this could be breaking.

**Comment by danfascia** [comment]
I have the same issue with this which I cannot wrap my head round

I'm trying to generate the breadcrumb trail to the current displayed page which I'm guessing is your exact use case too.

I try to use

```
---
eleventyNavigation:
  key: Chest
  parent: Groups
---
          {% set navPages = collections.all | eleventyNavigationBreadcrumb(eleventyNavigation.key) %}
          {% for item in navPages %} ...

```

It keeps telling me that the node bearing the node `Chest` is not found even though I'm defining it in the front matter of the same document template which renders the breadcrumb trail

**Comment by brettdewoody** [comment]
Similar issue for me. I'm trying to generate breadcrumbs for a page generated in a global data file (pulling from an API). I define an `eleventyNavigation` object on the data object (with a `key` and `parent`), and pass the key to `eleventyNavigationBreadcrumb` but get a `Node does not exist: [Node ID]` where `[Node ID]` is the key defined in the `eleventyNavigation` object.

Perhaps it's a data cascade issue - the parent page is built from a `/content` `.md` file. So at the time the page from the global data file is built Node doesn't know about the `/content` parent yet?

**Comment by wdporter** [comment]
{% set navPages = collections.all | eleventyNavigationBreadcrumb(eleventyNavigation.key, { includeSelf: true }) %}

**Comment by noelleleigh** [comment]
I also experienced this error and narrowed it down to using the [`eleventyExcludeFromCollections` option](https://www.11ty.dev/docs/collections/#option-exclude-content-from-collections) on a page that uses a parent template with breadcrumb-generation code.

I'm preparing a PR to allow the `eleventyNavigationBreadcrumb` function to return an empty array if the key it is searching for does not appear in the graph.

**Comment by JensLembke** [comment]
I run in the same issue. @noelleleigh could you describe your workaround more in detail?

This is what I'm trying:

`{% set crumbs = collections.all | eleventyNavigationBreadcrumb(eleventyNavigation.key) %}
{% for crumb in crumbs %}
  <a class="crumb" href="{{ crumb.url | url }}">{{ crumb.title }}</a>
{% endfor %}`

**Comment by zachleat** [comment]
Fixed by #39. Thank you! Shipping with 0.3.3

**Comment by mattcph** [comment]
Thanks for this thread, for casual viewers, note that the released key name in 3.3+ is: 'allowMissing'  (not 'handleMissing')

**Comment by inetbiz** [comment]
@noelleleigh 
# Error Output

```
[11ty] Problem writing Eleventy templates:
[11ty] 1. Having trouble rendering njk template ./_src/components/breadcrumb.njk (via TemplateContentRenderError)
  Eleventy:EleventyErrorHandler (error stack): TemplateContentRenderError: Having trouble rendering njk template ./_src/components/breadcrumb.njk
  Eleventy:EleventyErrorHandler     at Template._render (/home/denverpr/nodevenv/repositories/yada-11ty-bootstrap-theme/16/lib/node_modules/@11ty/eleventy/src/TemplateContent.js:455:15)
  Eleventy:EleventyErrorHandler     at processTicksAndRejections (node:internal/process/task_queues:96:5)
  Eleventy:EleventyErrorHandler     at async Template.getTemplateMapContent (/home/denverpr/nodevenv/repositories/yada-11ty-bootstrap-theme/16/lib/node_modules/@11ty/eleventy/src/Template.js:1077:19)
  Eleventy:EleventyErrorHandler     at async TemplateMap.populateContentDataInMap (/home/denverpr/nodevenv/repositories/yada-11ty-bootstrap-theme/16/lib/node_modules/@11ty/eleventy/src/TemplateMap.js:461:39)
  Eleventy:EleventyErrorHandler     at async TemplateMap.cache (/home/denverpr/nodevenv/repositories/yada-11ty-bootstrap-theme/16/lib/node_modules/@11ty/eleventy/src/TemplateMap.js:360:5)
  Eleventy:EleventyErrorHandler     at async TemplateWriter._createTemplateMap (/home/denverpr/nodevenv/repositories/yada-11ty-bootstrap-theme/16/lib/node_modules/@11ty/eleventy/src/TemplateWriter.js:244:5)
  Eleventy:EleventyErrorHandler     at async TemplateWriter.generateTemplates (/home/denverpr/nodevenv/repositories/yada-11ty-bootstrap-theme/16/lib/node_modules/@11ty/eleventy/src/TemplateWriter.js:277:5)
  Eleventy:EleventyErrorHandler     at async TemplateWriter.write (/home/denverpr/nodevenv/repositories/yada-11ty-bootstrap-theme/16/lib/node_modules/@11ty/eleventy/src/TemplateWriter.js:323:23)
  Eleventy:EleventyErrorHandler     at async Eleventy.executeBuild (/home/denverpr/nodevenv/repositories/yada-11ty-bootstrap-theme/16/lib/node_modules/@11ty/eleventy/src/Eleventy.js:1003:13) +0ms
[11ty] 2. (./_src/components/breadcrumb.njk)
[11ty]   Error: filter not found: eleventyNavigationBreadcrumb (via Template render error)
  Eleventy:EleventyErrorHandler (error stack): Template render error: (./_src/components/breadcrumb.njk)
  Eleventy:EleventyErrorHandler   Error: filter not found: eleventyNavigationBreadcrumb
  Eleventy:EleventyErrorHandler     at Object._prettifyError (/home/denverpr/nodevenv/repositories/yada-11ty-bootstrap-theme/16/lib/node_modules/nunjucks/src/lib.js:36:11)
  Eleventy:EleventyErrorHandler     at /home/denverpr/nodevenv/repositories/yada-11ty-bootstrap-theme/16/lib/node_modules/nunjucks/src/environment.js:563:19
  Eleventy:EleventyErrorHandler     at Template.root [as rootRenderFunc] (eval at _compile (/home/denverpr/nodevenv/repositories/yada-11ty-bootstrap-theme/16/lib/node_modules/nunjucks/src/environment.js:633:18), <anonymous>:60:3)
  Eleventy:EleventyErrorHandler     at Template.render (/home/denverpr/nodevenv/repositories/yada-11ty-bootstrap-theme/16/lib/node_modules/nunjucks/src/environment.js:552:10)
  Eleventy:EleventyErrorHandler     at /home/denverpr/nodevenv/repositories/yada-11ty-bootstrap-theme/16/lib/node_modules/@11ty/eleventy/src/Engines/Nunjucks.js:485:14
  Eleventy:EleventyErrorHandler     at new Promise (<anonymous>)
  Eleventy:EleventyErrorHandler     at /home/denverpr/nodevenv/repositories/yada-11ty-bootstrap-theme/16/lib/node_modules/@11ty/eleventy/src/Engines/Nunjucks.js:484:14
  Eleventy:EleventyErrorHandler     at Template._render (/home/denverpr/nodevenv/repositories/yada-11ty-bootstrap-theme/16/lib/node_modules/@11ty/eleventy/src/TemplateContent.js:432:28)
  Eleventy:EleventyErrorHandler     at processTicksAndRejections (node:internal/process/task_queues:96:5)
  Eleventy:EleventyErrorHandler     at async Template.getTemplateMapContent (/home/denverpr/nodevenv/repositories/yada-11ty-bootstrap-theme/16/lib/node_modules/@11ty/eleventy/src/Template.js:1077:19) +0ms
```
## Template File

```
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="#">Home</a></li>
    {% set navPages = collections.all | eleventyNavigationBreadcrumb(eleventyNavigation.key, {handleMissing: true}) %}
    {% for crumb in navPages %}
    <li class="breadcrumb-item{% if crumb.url == page.url %} active" aria-current="page">{{ crumb.title }}{% endif %}>{% else %}<a class="pretty-link" href="{{ crumb.url | url }}">{{ crumb.title }}</a>
  {%- endfor %}
  </ol>
</nav>
```

### Question

What or where should I look?

**Comment by zachleat** [comment]
@inetbiz Sounds like you might have forgot to `addPlugin` this one? https://www.11ty.dev/docs/plugins/navigation/#installation

**Comment by LudovicLambrechts** [comment]
Hi, thank you for this fix. I encountered the issue, which was indeed fixed by the allowMissing flag ;)

In my case, it turned out that my page hierarchy was wrong. On the top of the navigation tree, I had a reference to a non existing parent, which caused the error. Because of it, all pages in the faulty branch are missing the breadcrumbs. Additional symptom is the this branch did not appear in the content generated by the eleventyNavigationToHtml filter neither.

Hope this helps
