### ISSUE TITLE
Node dependency error with canary

### ISSUE THREAD

**Issue by mikeritter** [11ty/eleventy-navigation#30]
While using `"@11ty/eleventy": "^1.0.0-canary.15"` trying to install `@11ty/eleventy-navigation` I receive this error:

```
Could not resolve dependency:
npm ERR! peer @11ty/eleventy@">=0.7.0" from @11ty/eleventy-navigation@0.2.0
npm ERR! node_modules/@11ty/eleventy-navigation
npm ERR!   dev @11ty/eleventy-navigation@"*" from the root project
```

Is this because of the string in the branch/version name?

**Comment by zachleat** [comment]
Howdy, we’ve removed the peerDependency in 0.3.x and now check plugin compatibility using package.json -> 11ty value. The problem there is that canary releases in npm aren’t included in peer dependency checks (I don’t know agree with that but yeah).

![image](https://user-images.githubusercontent.com/39355/130078879-ac965498-9477-48ac-82aa-0d02c236748c.png)

https://semver.npmjs.com/

**Comment by mikeritter** [comment]
thanks. i've gone to using the stable releases.
