### ISSUE TITLE
doesn't seem to work

### ISSUE THREAD

**Issue by punund** [11ty/eleventy-navigation#4]
After using it like this

         <ol class="column is-one-fifth toc">
            {{ collections.all | eleventyNavigation | eleventyNavigationToHtml | safe }}
         </ol>
         <div class="column is-three-fifths">
            <div class="container">
               {{ content }}
            </div>
         <div class="column is-one-fifth">

it dumps raw data on me:

[{"template":{"inputPath":"./index.html","inputDir":".","parsed":{"root":"","dir":".","base":"index.html","ext":".html","name":"index","extname":".html","basename":"index.html","dirname":".","stem":"index","path":"./index.html","absolute":"...","isAbsolute":false},"extraOutputSubdirectory":"","outputDir":"_site","linters":[],"transforms":[],"plugins":{},"templateData":{"config":{"templateFormats":["liquid","ejs","md","hbs","mustache","haml","pug","njk","html","jstl","11ty.js"],"pathPrefix":"/","markdownTemplateEngine":"liquid","htmlTemplateEngine":"liquid","dataTemplateEngine":"liquid","passthroughFileCopy":true,"htmlOutputSuffix":"-o","jsDataFileSuffix":".11tydata","keys":{"package":"pkg","layout":"layout","permalink":"permalink","permalinkRoot":"permalinkBypassOutputDir","engineOverride":"templateEngineOverride"},"dir":{"input":".","includes":"_includes","data":"_data","output":"_site"},"filters":{},"handlebarsHelpers":{},"nunjucksFilters":

etc.

The content is showing fine.

**Comment by punund** [comment]
This was due to template ending in `.html` and not in `.njk`.

**Comment by zachleat** [comment]
Ah yeah first pass only includes rendering support in Nunjucks. More to come!
