### ISSUE TITLE
Empty array of navPages

### ISSUE THREAD

**Issue by kalininmax** [11ty/eleventy-navigation#45]
Browser:
![image](https://user-images.githubusercontent.com/20542636/185807162-3affdcea-51d7-4dae-a062-b3289f9a0791.png)

I'm newbie. I used [this guide](https://www.11ty.dev/docs/plugins/navigation/).

In my md files I used front matter keys like this:

```
---
title: 11ty starter site
description: This is a demonstration website generated using the 11ty static site generator.
layout: base.njk
eleventyNavigation:
	key: home
	order: 100
---
```

```
---
title: About us
description: What we do.
eleventyNavigation:
	key: about
	order: 200
---
```

```
---
title: Privacy policy
description: We keep your details private.
eleventyNavigation:
	key: privacy
	parent: about
	order: 220
---
```

```
---
title: Our team
description: Information about us.
eleventyNavigation:
	key: team
	parent: about
	order: 210
---
```

But it return empty array (screenshots above):
```
{% set navPages = collections.all | eleventyNavigation %}
{{ navPages | dump | safe }}  
```
What's problem with eleventy navigation in my project?
Repository: https://github.com/kalininmax/11ty

**Comment by pdehaan** [comment]
Instead of using tabs in your frontmatter, try using 2 spaces:

```json
[{"key":"home","order":100,"url":"/","pluginType":"eleventy-navigation","title":"home","children":[]},{"key":"about","order":200,"url":"/about/","pluginType":"eleventy-navigation","title":"about","children":[{"key":"team","parent":"about","order":210,"url":"/about/team/","pluginType":"eleventy-navigation","parentKey":"about","title":"team","children":[]},{"key":"privacy","parent":"about","order":220,"url":"/about/privacy/","pluginType":"eleventy-navigation","parentKey":"about","title":"privacy","children":[]}]}]
```

**Comment by kalininmax** [comment]
@pdehaan thank you so much.
Actually, just now, I found this answer in [Eleventy Walk Through](https://rphunt.github.io/eleventy-walkthrough/basic-data-and-templating-using-liquid.html) guide. But anyway thank you for your time.
![image](https://user-images.githubusercontent.com/20542636/185810940-d3423bac-9c4e-484e-83c9-d100e2105d7c.png)

**Comment by GRUBES** [comment]
FWIW it looks like this occurs because of [this condition](https://github.com/11ty/eleventy-navigation/blob/master/eleventy-navigation.js#L8). If you do not provide a specific `key` to `eleventyNavigation`, then the pages in the collection you pass _cannot_ have a `parent`. Not sure whether that is intentional, but it was unexpected to me.
